[package]
name = "dogma"
version = "0.1.0"
authors = ["Arto Bendiken <arto@bendiken.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
