[package]
name = "dogma"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = ["all", "std"]
all = ["enums", "path", "serde", "structs", "traits", "uuid"]
alloc = ["path", "dogma-traits?/alloc", "dogma-uuid?/alloc"]
std = ["alloc", "dogma-path?/std", "dogma-traits?/std", "dogma-uri?/std", "dogma-uuid?/std"]
unstable = []

# Enums:
enums = ["iri", "uri", "dogma-uri/enums"]
iri = ["alloc", "dep:dogma-uri", "dogma-uri/iri"]
uri = ["iri", "dogma-uri/uri"]

# Structs:
structs = ["iri", "uri", "dogma-uri/structs"]

# Traits:
traits = ["collection", "countable", "labeled", "named"]
collection = ["alloc", "dep:dogma-traits", "dogma-traits/collection"]
countable = ["dep:dogma-traits", "dogma-traits/countable"]
labeled = ["alloc", "dep:dogma-traits", "dogma-traits/labeled"]
named = ["alloc", "dep:dogma-traits", "dogma-traits/named"]

# Other component crates:
path = ["dep:dogma-path"]
uuid = ["dep:dogma-uuid"]

# Interop:
camino = ["std", "dogma-path/camino"]
clap = ["std", "dogma-uri?/clap"]
email-address = ["std", "uri", "dogma-uri/email-address"]
fluent-uri = ["uri", "dogma-uri/fluent-uri"]
iri-string = ["uri", "dogma-uri/iri-string"]
miette = ["std", "dogma-uri?/miette"]
serde = ["dogma-path?/serde", "dogma-traits?/serde", "dogma-uri?/serde", "dogma-uuid?/serde"]
url = ["uri", "dogma-uri/url"]

[dependencies]
dogma-traits = { workspace = true, optional = true }
dogma-path = { workspace = true, optional = true }
dogma-uri = { workspace = true, optional = true }
dogma-uuid = { workspace = true, optional = true }

[dev-dependencies]
serde_test.workspace = true
clap.workspace = true
miette.workspace = true
